trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    version: '16.x'

- script: |
    npm install
  displayName: 'NpmInstall'

- script: |
    npm run build
  displayName: 'NpmBuild'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: SampleAngular14
    targetPath: '$(Build.SourcesDirectory)/dist'
    publishLocation: 'pipeline'
  displayName: 'PublishNpmArtifact'